bin/slt-stage.rb

@kraman this is what is preventing new packages from being published to staging automatically.

slt-stage: ensure version list is a list

---

bin/slt-changelog.rb

I've tested it with repos that have never been released, where HEAD == latest release, and multiple branches of loopback and loopback-boot, and in all cases the result is a drastic improvement in accuracy and consistency.
@bajtos this one is for you, it's the real fix for #22

Support divergent changelogs on release branches

---

bin/slt-changelog.rb

Use double quotes to quote git arguments, because singe quotes are
passed as-is on Windows and cause in errors, like
unknown revision '12309'
(Notice that the revision string includes single quotes from
command-line arguments.)
/to @rmg please review
/cc @sam-github 
With this patch in place, I was able to successfully complete a dry run of `slt-release` on Windows using Git Bash, native (win32) Ruby and native (win32) Node.js.

slt-changelog: fix for Windows

---

bin/slt.js
index.js
lib/DUAL_ARTISTIC.tpl
lib/DUAL_MIT.tpl
lib/STRONGLOOP.tpl
lib/license.js
package.json

It detects obsolete license specifications used by StrongLoop, and
converts them to a currently valid specification.
It also rewrites the LICENSE or LICENSE.md file for a valid license
specification, guaranteeing consistent text for all license files.
The existence of the tool should help keep current packages consistent,
as well as allowing any future changes we decide to make to the
licensing (such as adjustments to the format of the license files) much
easier, perhaps trivial.
connected to strongloop-internal/scrum-nodeops#871

Add fix-license command

---

bin/slt-changelog.js
bin/slt-changelog.rb
package.json

Node: 204 lines
Ruby: 149 lines
It's not as much longer as I feared it might be. I think a lot of that is owed to how well Promises mix with my style of functional programming.
Note that these produce identical output in the "bug compatible" sense, and the commit that fixes the version commit filtering fixes that bug in both versions of the command.

Rewrite slt-changelog in JavaScript

---

bin/slt-release.sh
lib/blip.js
lib/project.js
lib/version.js
test/test-version-blip.js

Algorithm:
1. If sl-blip is detected in optionalDependencies, scripts.preinstall, scripts.install, or scripts.postinstall:
1. overwrite scripts/sl-blip.js with latest version
2. remove from optionalDependencies
3. if not in scripts.preinstall, scripts.install, or scripts.postinstall:
1. add to first unused install phase script
@gunjpan I was unsure how to describe in comments how I wanted #39 to look. I also merged #40 which would require you to rebase and resolve a bunch of conflicts. Rather than make you resolve the conflicts and us go back and forth in comments, I figured it would probably be faster if I just showed you how I would write it.
Connect to strongloop-internal/scrum-loopback#643
Connect to strongloop-internal/scrum-nodeops#1079
Replaces #39

Use script version of sl-blip

---

lib/blip.js

There's no reason to use http here, honestly.
See https://github.com/strongloop/loopback/issues/1079#issuecomment-172551927
/cc @STRML

blip: use https instead of http

---

bin/slt-stage.rb

Any arguments that are given are passed along to 'npm publish' when it
is run as the last step. This allows the publish to be done against a
different registry than the install, which is required when using a
restricted proxy.
Example usage:
```
export npm_config_registry=http://readonly/
slt-stage --registry=http://read-write/
```

add argument forwarding support to slt-stage

---

lib/project.js
test/test-version-blip.js

No matter how foolproof the JS is and how explicitly it tries to always
exit with 0, none of that matters if node isn't in the path for some
reason.
To handle this, add a simple `|| exit 0` to the end of the script entry
in package.json.
Also make sure we "upgrade" the previous style if we see it being used.

change blip script to not depend on node

---

bin/slt-changelog.js

The fix was pretty obvious once I compared it side-by-side to the Ruby version.

Fix first release

---

bin/slt-release.sh

Don't bother creating and updating the major-release tracking branches
that slt-release previously created. They aren't actually useful or
meaningful and have only caused confusion when people see them.
They were originally inteaded as a sign-post indicating what the most
recent release tag of a given major version was, since that may or may
not be the HEAD of a given branch, despite the HEAD of a given branch
having the same version specified in its package.json.

slt-release: remove use of X.x-latest branches

---

bin/slt-release.sh
bin/slt-stage.rb

There is no value, and some non-zero risk, from distributing CI config files that may contain sensitive information about infrastructure.

prevent publishing of CI related files

---

bin/slt-release.sh
bin/slt-stage.rb
lib/info.js
test/test-info.js

In the rare case that a package _really_ wants to include its `test` folder in its published tarball, this can be done by adding a `publishConfig.export-tests` property in package.json:
```json
{
"name": "my-package",
"publishConfig": {
"export-tests": true
}
}
```

Allow test folder to be published

---

bin/slt.ejs
lib/APACHE.tpl
lib/cla.js
lib/copyright.js
lib/license.js
test/test-copyright.js
test/test-license.js

Add support for doing `slt license --apache` to inject/update a project to use the Apache 2.0 license.
Also adds some basic tests for `slt license` since they were completely missing.

add support for Apache-2.0 license

---

index.js
lib/shrinkwrap.js
test/shrinkwrap-after.json
test/shrinkwrap-fixture.json
test/test-shrinkwrap.js

When using shrinkwrap, combined with a private staging registry, you may
not want your internal registry's URLs baked in to the
npm-shrinkwrap.json file that gets created. This utility strips out
those fields.

slt: add shrinkwrap cmd for filtering fields

---

bin/slt-release.sh

If no version or increment is given, use the version that is in
package.json for the release.
After the version has been identified, by argument, increment, or
package.json, THEN validate it for suitability.
The version must be:
- unreleased on the registry being used
- untagged in the git repository
- a valid SemVer version string
If all of these criteria are met, then proceed to cut the release.

slt-release: fallback to package.json for version

---

README.md
bin/slt-release.sh
bin/slt.ejs
bin/slt.js
lib/shrinkwrap.js

Addresses a couple bugs reported as comments on #56.

fix shrinkwrap and clean up docs

---

bin/slt-release.sh

Also tell the user what changes are being made and how to clean up after the package was published.
@rmg please review
cc @sam-github 
I don't have a sandbox to test this change, so I didn't run the new code. What's the best way of testing slt-release without messing up github/npmjs data?

slt-release: don't add npmignore entries twice

---

lib/copyright.js
lib/lint.js
lib/project.js
lib/shrinkwrap.js
lib/version.js
test/test-cla.js
test/test-copyright.js
test/test-license.js
test/test-project.js
test/test-shrinkwrap.js
test/test-version.js

Adds tests where missing and refactors code slightly where it improves testability.

Expand test coverage

---

LICENSE
lib/paths.js

Just extends the `**/*.js` filter to `**/*.{js,ts}`.

add support for TypeScript when updating copyrights

---

lib/copyright.js

The copyright.owner and copyright.identifier properties can be supplied
in the package's package.json to override the use of author and package
name in copyright statements.

add copyright.owner/identifier support

---

.eslintrc.json
.travis.yml
bin/slt-release.sh
lib/license.js
lib/project.js
lib/shrinkwrap.js
lib/wrapped.js
package.json
test/test-project.js

It is nice when the version number in package.json matches the version
numbers in package-lock.json and npm-shrinkwrap.json when they are being
used. They should be treated the same way bower.json is treated.
Resolves #83

feat: bump versions in lock files if present
